version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - HDFS_CONF_dfs_replication=1
    volumes:
      - ./input:/input_data
      - ./build:/job
      - ./run-jobs.sh:/run-jobs.sh
      - ./lib/external:/external_libs
      - ./output_graphs:/charts_output  
    ports:
      - "9870:9870"
      - "9000:9000"
    depends_on:
      - datanode1
      - datanode2
      - datanode3

  datanode1:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode1
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SERVICE_PRECONDITION=namenode:9000
    volumes:
      - hadoop_datanode1:/hadoop/dfs/data

  datanode2:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode2
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SERVICE_PRECONDITION=namenode:9000
    volumes:
      - hadoop_datanode2:/hadoop/dfs/data
  
  datanode3:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode3
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
      - SERVICE_PRECONDITION=namenode:9000
    volumes:
      - hadoop_datanode3:/hadoop/dfs/data  

volumes:
  hadoop_datanode1:
  hadoop_datanode2:
  hadoop_datanode3:
